### ISSUE TITLE
لا تُعِد اختراع العجلة

### ISSUE THREAD

**Issue by AliOsm** [MagedSaeed/ubuntu-post-install#1]
ألقي نظرة على هذا يا هذا:
https://omakub.org

**Comment by MagedSaeed** [comment]
مرحبا بالعزيز علي، شكرا جزيلا على الاقتراح،،

المشكلة في مثل هذا ال setup إنه ينزل أشياء ربما ما أحتاجها، وباعتقادي إن هذا اختيارات فريدة لكل شخص، بالنسبة لي، معي مجموعة من ال tools  احتاجهم سواء لو أنا في بيئة GUI أو بيئة command line واحتاج أنزلهم ب script واحد.

للأمانة، لقيت في هذي ال tool كثير من البرمجيات التي تستحق النظر والتجربة،، شكرا مرة أخرى،،
